# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='\u89c6\u9891\u94fe\u63a5'),
            preserve_default=False,
        ),
    ]
